spring.application.name=gestion-tareas-spring-mongodb
spring.data.mongodb.uri=mongodb://localhost:27017/bd_tareas
spring.data.mongodb.database=bd_tareas
server.port=8080
logging.level.org.springframework=INFO